import type { ServiceTemplate } from "./types";

export const SERVICE_CATALOG: ServiceTemplate[] = [
  // ── Databases ────────────────────────────────────────────────────────
  {
    id: "postgres",
    name: "PostgreSQL",
    image: "postgres",
    category: "database",
    description: "The world's most advanced open source relational database.",
    defaultPort: 5432,
    icon: "🐘",
    fields: [
      { key: "POSTGRES_DB",       label: "Database name",  type: "string",  default: "mydb",     isEnvVar: true },
      { key: "POSTGRES_USER",     label: "Username",       type: "string",  default: "postgres",  isEnvVar: true },
      { key: "POSTGRES_PASSWORD", label: "Password",       type: "string",  default: "password",  isEnvVar: true },
    ],
    defaultVolumes: ["postgres_data:/var/lib/postgresql/data"],
  },
  {
    id: "mysql",
    name: "MySQL",
    image: "mysql",
    category: "database",
    description: "The most popular open source SQL database.",
    defaultPort: 3306,
    icon: "🐬",
    fields: [
      { key: "MYSQL_DATABASE",      label: "Database name",   type: "string", default: "mydb",     isEnvVar: true },
      { key: "MYSQL_USER",          label: "Username",        type: "string", default: "user",     isEnvVar: true },
      { key: "MYSQL_PASSWORD",      label: "Password",        type: "string", default: "password", isEnvVar: true },
      { key: "MYSQL_ROOT_PASSWORD", label: "Root password",   type: "string", default: "rootpass", isEnvVar: true },
    ],
    defaultVolumes: ["mysql_data:/var/lib/mysql"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    image: "mongo",
    category: "database",
    description: "The most popular NoSQL document database.",
    defaultPort: 27017,
    icon: "🍃",
    fields: [
      { key: "MONGO_INITDB_ROOT_USERNAME", label: "Root username", type: "string", default: "admin",    isEnvVar: true },
      { key: "MONGO_INITDB_ROOT_PASSWORD", label: "Root password", type: "string", default: "password", isEnvVar: true },
      { key: "MONGO_INITDB_DATABASE",      label: "Database name", type: "string", default: "mydb",     isEnvVar: true },
    ],
    defaultVolumes: ["mongo_data:/data/db"],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    image: "mariadb",
    category: "database",
    description: "Community-developed fork of MySQL.",
    defaultPort: 3306,
    icon: "🦭",
    fields: [
      { key: "MARIADB_DATABASE",      label: "Database name",  type: "string", default: "mydb",     isEnvVar: true },
      { key: "MARIADB_USER",          label: "Username",       type: "string", default: "user",     isEnvVar: true },
      { key: "MARIADB_PASSWORD",      label: "Password",       type: "string", default: "password", isEnvVar: true },
      { key: "MARIADB_ROOT_PASSWORD", label: "Root password",  type: "string", default: "rootpass", isEnvVar: true },
    ],
    defaultVolumes: ["mariadb_data:/var/lib/mysql"],
  },

  // ── Cache ─────────────────────────────────────────────────────────────
  {
    id: "redis",
    name: "Redis",
    image: "redis",
    category: "cache",
    description: "In-memory data structure store, used as cache and message broker.",
    defaultPort: 6379,
    icon: "⚡",
    fields: [],
    defaultVolumes: ["redis_data:/data"],
  },
  {
    id: "memcached",
    name: "Memcached",
    image: "memcached",
    category: "cache",
    description: "High-performance distributed memory caching system.",
    defaultPort: 11211,
    icon: "🗂️",
    fields: [],
  },

  // ── Messaging ─────────────────────────────────────────────────────────
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    image: "rabbitmq",
    category: "messaging",
    description: "Open source message broker supporting AMQP.",
    defaultPort: 5672,
    icon: "🐇",
    fields: [
      { key: "RABBITMQ_DEFAULT_USER", label: "Username", type: "string", default: "admin",    isEnvVar: true },
      { key: "RABBITMQ_DEFAULT_PASS", label: "Password", type: "string", default: "password", isEnvVar: true },
    ],
    defaultVolumes: ["rabbitmq_data:/var/lib/rabbitmq"],
  },
  {
    id: "kafka",
    name: "Apache Kafka",
    image: "confluentinc/cp-kafka",
    category: "messaging",
    description: "Distributed event streaming platform.",
    defaultPort: 9092,
    icon: "📨",
    fields: [
      { key: "KAFKA_BROKER_ID",                           label: "Broker ID",         type: "number", default: 1,                             isEnvVar: true },
      { key: "KAFKA_ZOOKEEPER_CONNECT",                   label: "Zookeeper connect", type: "string", default: "zookeeper:2181",              isEnvVar: true },
      { key: "KAFKA_ADVERTISED_LISTENERS",                label: "Advertised listeners", type: "string", default: "PLAINTEXT://localhost:9092", isEnvVar: true },
    ],
  },
  {
    id: "activemq",
    name: "ActiveMQ",
    image: "apache/activemq-classic",
    category: "messaging",
    description: "Open source multi-protocol messaging broker.",
    defaultPort: 61616,
    icon: "📬",
    fields: [],
    defaultVolumes: ["activemq_data:/var/lib/activemq/data"],
  },

  // ── Web Servers ───────────────────────────────────────────────────────
  {
    id: "nginx",
    name: "Nginx",
    image: "nginx",
    category: "webserver",
    description: "High-performance HTTP server and reverse proxy.",
    defaultPort: 80,
    icon: "🌐",
    fields: [],
    defaultVolumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"],
  },
  {
    id: "traefik",
    name: "Traefik",
    image: "traefik",
    category: "webserver",
    description: "Cloud-native reverse proxy and load balancer.",
    defaultPort: 80,
    icon: "🔀",
    fields: [],
    defaultVolumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
  },
  {
    id: "caddy",
    name: "Caddy",
    image: "caddy",
    category: "webserver",
    description: "Fast, multi-platform web server with automatic HTTPS.",
    defaultPort: 80,
    icon: "🏠",
    fields: [],
    defaultVolumes: ["caddy_data:/data", "caddy_config:/config"],
  },

  // ── Monitoring ────────────────────────────────────────────────────────
  {
    id: "prometheus",
    name: "Prometheus",
    image: "prom/prometheus",
    category: "monitoring",
    description: "Monitoring system and time series database.",
    defaultPort: 9090,
    icon: "🔥",
    fields: [],
    defaultVolumes: ["prometheus_data:/prometheus", "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"],
  },
  {
    id: "grafana",
    name: "Grafana",
    image: "grafana/grafana",
    category: "monitoring",
    description: "Open source analytics and interactive visualization.",
    defaultPort: 3000,
    icon: "📊",
    fields: [
      { key: "GF_SECURITY_ADMIN_USER",     label: "Admin user",     type: "string", default: "admin",    isEnvVar: true },
      { key: "GF_SECURITY_ADMIN_PASSWORD", label: "Admin password", type: "string", default: "admin",    isEnvVar: true },
    ],
    defaultVolumes: ["grafana_data:/var/lib/grafana"],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    image: "elasticsearch",
    category: "monitoring",
    description: "Distributed search and analytics engine.",
    defaultPort: 9200,
    icon: "🔍",
    fields: [
      { key: "discovery.type", label: "Discovery type", type: "string", default: "single-node", isEnvVar: true },
      { key: "xpack.security.enabled", label: "Security enabled", type: "string", default: "false", isEnvVar: true },
    ],
    defaultVolumes: ["es_data:/usr/share/elasticsearch/data"],
  },

  // ── Dev Tools ─────────────────────────────────────────────────────────
  {
    id: "adminer",
    name: "Adminer",
    image: "adminer",
    category: "devtools",
    description: "Full-featured database management tool in a single file.",
    defaultPort: 8080,
    icon: "🛠️",
    fields: [],
  },
  {
    id: "mailhog",
    name: "MailHog",
    image: "mailhog/mailhog",
    category: "devtools",
    description: "Email testing tool for developers.",
    defaultPort: 8025,
    icon: "📧",
    fields: [],
  },
  {
    id: "minio",
    name: "MinIO",
    image: "minio/minio",
    category: "devtools",
    description: "S3-compatible object storage for local development.",
    defaultPort: 9000,
    icon: "🗄️",
    fields: [
      { key: "MINIO_ROOT_USER",     label: "Root user",     type: "string", default: "minioadmin", isEnvVar: true },
      { key: "MINIO_ROOT_PASSWORD", label: "Root password", type: "string", default: "minioadmin", isEnvVar: true },
    ],
    defaultVolumes: ["minio_data:/data"],
  },
  {
    id: "portainer",
    name: "Portainer",
    image: "portainer/portainer-ce",
    category: "devtools",
    description: "Container management UI for Docker.",
    defaultPort: 9000,
    icon: "🐋",
    fields: [],
    defaultVolumes: ["/var/run/docker.sock:/var/run/docker.sock", "portainer_data:/data"],
  },
];

export const CATEGORIES = [
  { id: "all",        label: "All" },
  { id: "database",  label: "Databases" },
  { id: "cache",     label: "Cache" },
  { id: "messaging", label: "Messaging" },
  { id: "webserver", label: "Web Servers" },
  { id: "monitoring",label: "Monitoring" },
  { id: "devtools",  label: "Dev Tools" },
] as const;
