import type { ServiceTemplate } from "./types";

export const SERVICE_CATALOG: ServiceTemplate[] = [
  // ── Databases ────────────────────────────────────────────────────────
  {
    id: "postgres",
    name: "PostgreSQL",
    image: "postgres",
    category: "database",
    description: "The world's most advanced open source relational database.",
    defaultPort: 5432,
    icon: "🐘",
    fields: [
      { key: "POSTGRES_DB",       label: "Database name",  type: "string",  default: "mydb",     isEnvVar: true },
      { key: "POSTGRES_USER",     label: "Username",       type: "string",  default: "postgres",  isEnvVar: true },
      { key: "POSTGRES_PASSWORD", label: "Password",       type: "string",  default: "password",  isEnvVar: true },
    ],
    defaultVolumes: ["postgres_data:/var/lib/postgresql/data"],
  },
  {
    id: "mysql",
    name: "MySQL",
    image: "mysql",
    category: "database",
    description: "The most popular open source SQL database.",
    defaultPort: 3306,
    icon: "🐬",
    fields: [
      { key: "MYSQL_DATABASE",      label: "Database name",   type: "string", default: "mydb",     isEnvVar: true },
      { key: "MYSQL_USER",          label: "Username",        type: "string", default: "user",     isEnvVar: true },
      { key: "MYSQL_PASSWORD",      label: "Password",        type: "string", default: "password", isEnvVar: true },
      { key: "MYSQL_ROOT_PASSWORD", label: "Root password",   type: "string", default: "rootpass", isEnvVar: true },
    ],
    defaultVolumes: ["mysql_data:/var/lib/mysql"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    image: "mongo",
    category: "database",
    description: "The most popular NoSQL document database.",
    defaultPort: 27017,
    icon: "🍃",
    fields: [
      { key: "MONGO_INITDB_ROOT_USERNAME", label: "Root username", type: "string", default: "admin",    isEnvVar: true },
      { key: "MONGO_INITDB_ROOT_PASSWORD", label: "Root password", type: "string", default: "password", isEnvVar: true },
      { key: "MONGO_INITDB_DATABASE",      label: "Database name", type: "string", default: "mydb",     isEnvVar: true },
    ],
    defaultVolumes: ["mongo_data:/data/db"],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    image: "mariadb",
    category: "database",
    description: "Community-developed fork of MySQL.",
    defaultPort: 3306,
    icon: "🦭",
    fields: [
      { key: "MARIADB_DATABASE",      label: "Database name",  type: "string", default: "mydb",     isEnvVar: true },
      { key: "MARIADB_USER",          label: "Username",       type: "string", default: "user",     isEnvVar: true },
      { key: "MARIADB_PASSWORD",      label: "Password",       type: "string", default: "password", isEnvVar: true },
      { key: "MARIADB_ROOT_PASSWORD", label: "Root password",  type: "string", default: "rootpass", isEnvVar: true },
    ],
    defaultVolumes: ["mariadb_data:/var/lib/mysql"],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    image: "clickhouse/clickhouse-server",
    category: "database",
    description: "Blazing-fast OLAP database for real-time analytics at scale.",
    defaultPort: 8123,
    icon: "🖱️",
    fields: [
      { key: "CLICKHOUSE_DB",       label: "Database name", type: "string", default: "mydb",    isEnvVar: true },
      { key: "CLICKHOUSE_USER",     label: "Username",      type: "string", default: "user",    isEnvVar: true },
      { key: "CLICKHOUSE_PASSWORD", label: "Password",      type: "string", default: "password",isEnvVar: true },
    ],
    defaultVolumes: ["clickhouse_data:/var/lib/clickhouse"],
  },
  {
    id: "influxdb",
    name: "InfluxDB",
    image: "influxdb",
    category: "database",
    description: "Purpose-built time series database for metrics and events.",
    defaultPort: 8086,
    icon: "📈",
    fields: [
      { key: "DOCKER_INFLUXDB_INIT_MODE",     label: "Init mode",   type: "string", default: "setup",    isEnvVar: true },
      { key: "DOCKER_INFLUXDB_INIT_USERNAME", label: "Username",    type: "string", default: "admin",    isEnvVar: true },
      { key: "DOCKER_INFLUXDB_INIT_PASSWORD", label: "Password",    type: "string", default: "password", isEnvVar: true },
      { key: "DOCKER_INFLUXDB_INIT_ORG",      label: "Org name",    type: "string", default: "myorg",    isEnvVar: true },
      { key: "DOCKER_INFLUXDB_INIT_BUCKET",   label: "Bucket name", type: "string", default: "mybucket", isEnvVar: true },
    ],
    defaultVolumes: ["influxdb_data:/var/lib/influxdb2"],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    image: "neo4j",
    category: "database",
    description: "Leading graph database for highly connected data.",
    defaultPort: 7474,
    icon: "🕸️",
    fields: [
      { key: "NEO4J_AUTH", label: "Auth (user/password)", type: "string", default: "neo4j/password", isEnvVar: true },
    ],
    defaultVolumes: ["neo4j_data:/data", "neo4j_logs:/logs"],
  },
  {
    id: "cassandra",
    name: "Cassandra",
    image: "cassandra",
    category: "database",
    description: "Highly scalable NoSQL database for massive write-heavy workloads.",
    defaultPort: 9042,
    icon: "💎",
    fields: [],
    defaultVolumes: ["cassandra_data:/var/lib/cassandra"],
  },
  {
    id: "dynamodb-local",
    name: "DynamoDB Local",
    image: "amazon/dynamodb-local",
    category: "database",
    description: "Local emulator for AWS DynamoDB, ideal for offline development.",
    defaultPort: 8000,
    icon: "☁️",
    fields: [],
  },

  // ── Cache ─────────────────────────────────────────────────────────────
  {
    id: "redis",
    name: "Redis",
    image: "redis",
    category: "cache",
    description: "In-memory data structure store, used as cache and message broker.",
    defaultPort: 6379,
    icon: "⚡",
    fields: [],
    defaultVolumes: ["redis_data:/data"],
  },
  {
    id: "memcached",
    name: "Memcached",
    image: "memcached",
    category: "cache",
    description: "High-performance distributed memory caching system.",
    defaultPort: 11211,
    icon: "🗂️",
    fields: [],
  },

  // ── Messaging ─────────────────────────────────────────────────────────
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    image: "rabbitmq",
    category: "messaging",
    description: "Open source message broker supporting AMQP.",
    defaultPort: 5672,
    icon: "🐇",
    fields: [
      { key: "RABBITMQ_DEFAULT_USER", label: "Username", type: "string", default: "admin",    isEnvVar: true },
      { key: "RABBITMQ_DEFAULT_PASS", label: "Password", type: "string", default: "password", isEnvVar: true },
    ],
    defaultVolumes: ["rabbitmq_data:/var/lib/rabbitmq"],
  },
  {
    id: "kafka",
    name: "Apache Kafka",
    image: "confluentinc/cp-kafka",
    category: "messaging",
    description: "Distributed event streaming platform.",
    defaultPort: 9092,
    icon: "📨",
    fields: [
      { key: "KAFKA_BROKER_ID",                           label: "Broker ID",         type: "number", default: 1,                             isEnvVar: true },
      { key: "KAFKA_ZOOKEEPER_CONNECT",                   label: "Zookeeper connect", type: "string", default: "zookeeper:2181",              isEnvVar: true },
      { key: "KAFKA_ADVERTISED_LISTENERS",                label: "Advertised listeners", type: "string", default: "PLAINTEXT://localhost:9092", isEnvVar: true },
    ],
  },
  {
    id: "activemq",
    name: "ActiveMQ",
    image: "apache/activemq-classic",
    category: "messaging",
    description: "Open source multi-protocol messaging broker.",
    defaultPort: 61616,
    icon: "📬",
    fields: [],
    defaultVolumes: ["activemq_data:/var/lib/activemq/data"],
  },
  {
    id: "zookeeper",
    name: "Zookeeper",
    image: "confluentinc/cp-zookeeper",
    category: "messaging",
    description: "Distributed coordination service, required by Apache Kafka.",
    defaultPort: 2181,
    icon: "🦁",
    fields: [
      { key: "ZOOKEEPER_CLIENT_PORT", label: "Client port", type: "number", default: 2181, isEnvVar: true },
      { key: "ZOOKEEPER_TICK_TIME",   label: "Tick time",   type: "number", default: 2000, isEnvVar: true },
    ],
  },
  {
    id: "nats",
    name: "NATS",
    image: "nats",
    category: "messaging",
    description: "Ultra-lightweight and high-performance cloud native messaging system.",
    defaultPort: 4222,
    icon: "🚀",
    fields: [],
  },
  {
    id: "mosquitto",
    name: "Mosquitto (MQTT)",
    image: "eclipse-mosquitto",
    category: "messaging",
    description: "Lightweight MQTT message broker, widely used in IoT applications.",
    defaultPort: 1883,
    icon: "📡",
    fields: [],
    defaultVolumes: ["mosquitto_data:/mosquitto/data", "mosquitto_logs:/mosquitto/log"],
  },

  // ── Web Servers ───────────────────────────────────────────────────────
  {
    id: "nginx",
    name: "Nginx",
    image: "nginx",
    category: "webserver",
    description: "High-performance HTTP server and reverse proxy.",
    defaultPort: 80,
    icon: "🌐",
    fields: [],
    defaultVolumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"],
  },
  {
    id: "traefik",
    name: "Traefik",
    image: "traefik",
    category: "webserver",
    description: "Cloud-native reverse proxy and load balancer.",
    defaultPort: 80,
    icon: "🔀",
    fields: [],
    defaultVolumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
  },
  {
    id: "caddy",
    name: "Caddy",
    image: "caddy",
    category: "webserver",
    description: "Fast, multi-platform web server with automatic HTTPS.",
    defaultPort: 80,
    icon: "🏠",
    fields: [],
    defaultVolumes: ["caddy_data:/data", "caddy_config:/config"],
  },

  // ── Monitoring ────────────────────────────────────────────────────────
  {
    id: "prometheus",
    name: "Prometheus",
    image: "prom/prometheus",
    category: "monitoring",
    description: "Monitoring system and time series database.",
    defaultPort: 9090,
    icon: "🔥",
    fields: [],
    defaultVolumes: ["prometheus_data:/prometheus", "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"],
  },
  {
    id: "grafana",
    name: "Grafana",
    image: "grafana/grafana",
    category: "monitoring",
    description: "Open source analytics and interactive visualization.",
    defaultPort: 3000,
    icon: "📊",
    fields: [
      { key: "GF_SECURITY_ADMIN_USER",     label: "Admin user",     type: "string", default: "admin",    isEnvVar: true },
      { key: "GF_SECURITY_ADMIN_PASSWORD", label: "Admin password", type: "string", default: "admin",    isEnvVar: true },
    ],
    defaultVolumes: ["grafana_data:/var/lib/grafana"],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    image: "elasticsearch",
    category: "monitoring",
    description: "Distributed search and analytics engine.",
    defaultPort: 9200,
    icon: "🔍",
    fields: [
      { key: "discovery.type", label: "Discovery type", type: "string", default: "single-node", isEnvVar: true },
      { key: "xpack.security.enabled", label: "Security enabled", type: "string", default: "false", isEnvVar: true },
    ],
    defaultVolumes: ["es_data:/usr/share/elasticsearch/data"],
  },
  {
    id: "kibana",
    name: "Kibana",
    image: "kibana",
    category: "monitoring",
    description: "Data visualization dashboard for Elasticsearch.",
    defaultPort: 5601,
    icon: "📉",
    fields: [
      { key: "ELASTICSEARCH_HOSTS", label: "Elasticsearch URL", type: "string", default: "http://elasticsearch:9200", isEnvVar: true },
    ],
  },
  {
    id: "loki",
    name: "Grafana Loki",
    image: "grafana/loki",
    category: "monitoring",
    description: "Log aggregation system designed to work with Grafana.",
    defaultPort: 3100,
    icon: "📋",
    fields: [],
    defaultVolumes: ["loki_data:/loki"],
  },
  {
    id: "jaeger",
    name: "Jaeger",
    image: "jaegertracing/all-in-one",
    category: "monitoring",
    description: "End-to-end distributed tracing for microservices.",
    defaultPort: 16686,
    icon: "🔭",
    fields: [
      { key: "COLLECTOR_ZIPKIN_HOST_PORT", label: "Zipkin port", type: "string", default: ":9411", isEnvVar: true },
    ],
  },
  {
    id: "zipkin",
    name: "Zipkin",
    image: "openzipkin/zipkin",
    category: "monitoring",
    description: "Distributed tracing system to gather timing data.",
    defaultPort: 9411,
    icon: "🗺️",
    fields: [],
  },
  {
    id: "opensearch",
    name: "OpenSearch",
    image: "opensearchproject/opensearch",
    category: "monitoring",
    description: "AWS-backed open source fork of Elasticsearch.",
    defaultPort: 9200,
    icon: "🔎",
    fields: [
      { key: "discovery.type",                  label: "Discovery type",  type: "string", default: "single-node", isEnvVar: true },
      { key: "OPENSEARCH_INITIAL_ADMIN_PASSWORD",label: "Admin password", type: "string", default: "Admin@1234!",  isEnvVar: true },
    ],
    defaultVolumes: ["opensearch_data:/usr/share/opensearch/data"],
  },
  {
    id: "meilisearch",
    name: "Meilisearch",
    image: "getmeili/meilisearch",
    category: "monitoring",
    description: "Lightning-fast, typo-tolerant open source search engine.",
    defaultPort: 7700,
    icon: "⚡",
    fields: [
      { key: "MEILI_MASTER_KEY", label: "Master key", type: "string", default: "masterKey", isEnvVar: true },
    ],
    defaultVolumes: ["meilisearch_data:/meili_data"],
  },

  // ── Auth / API Gateway ────────────────────────────────────────────────
  {
    id: "keycloak",
    name: "Keycloak",
    image: "quay.io/keycloak/keycloak",
    category: "devtools",
    description: "Enterprise-grade SSO and Identity Provider for modern apps.",
    defaultPort: 8080,
    icon: "🔐",
    fields: [
      { key: "KEYCLOAK_ADMIN",          label: "Admin user",     type: "string", default: "admin",    isEnvVar: true },
      { key: "KEYCLOAK_ADMIN_PASSWORD", label: "Admin password", type: "string", default: "password", isEnvVar: true },
      { key: "KC_DB",                   label: "Database type",  type: "string", default: "postgres",  isEnvVar: true },
    ],
    defaultVolumes: ["keycloak_data:/opt/keycloak/data"],
  },
  {
    id: "vault",
    name: "HashiCorp Vault",
    image: "hashicorp/vault",
    category: "devtools",
    description: "Secrets management, encryption as a service, and privileged access.",
    defaultPort: 8200,
    icon: "🔒",
    fields: [
      { key: "VAULT_DEV_ROOT_TOKEN_ID",  label: "Root token",    type: "string", default: "root",            isEnvVar: true },
      { key: "VAULT_DEV_LISTEN_ADDRESS", label: "Listen address",type: "string", default: "0.0.0.0:8200",    isEnvVar: true },
    ],
  },
  {
    id: "kong",
    name: "Kong Gateway",
    image: "kong",
    category: "devtools",
    description: "Cloud-native API gateway and service mesh.",
    defaultPort: 8000,
    icon: "🦍",
    fields: [
      { key: "KONG_DATABASE",        label: "Database",    type: "string", default: "off",          isEnvVar: true },
      { key: "KONG_PROXY_ACCESS_LOG",label: "Access log",  type: "string", default: "/dev/stdout",  isEnvVar: true },
      { key: "KONG_ADMIN_LISTEN",    label: "Admin listen",type: "string", default: "0.0.0.0:8001", isEnvVar: true },
    ],
  },

  // ── Dev Tools ─────────────────────────────────────────────────────────
  {
    id: "adminer",
    name: "Adminer",
    image: "adminer",
    category: "devtools",
    description: "Full-featured database management tool in a single file.",
    defaultPort: 8080,
    icon: "🛠️",
    fields: [],
  },
  {
    id: "mailhog",
    name: "MailHog",
    image: "mailhog/mailhog",
    category: "devtools",
    description: "Email testing tool for developers.",
    defaultPort: 8025,
    icon: "📧",
    fields: [],
  },
  {
    id: "minio",
    name: "MinIO",
    image: "minio/minio",
    category: "devtools",
    description: "S3-compatible object storage for local development.",
    defaultPort: 9000,
    icon: "🗄️",
    fields: [
      { key: "MINIO_ROOT_USER",     label: "Root user",     type: "string", default: "minioadmin", isEnvVar: true },
      { key: "MINIO_ROOT_PASSWORD", label: "Root password", type: "string", default: "minioadmin", isEnvVar: true },
    ],
    defaultVolumes: ["minio_data:/data"],
  },
  {
    id: "portainer",
    name: "Portainer",
    image: "portainer/portainer-ce",
    category: "devtools",
    description: "Container management UI for Docker.",
    defaultPort: 9000,
    icon: "🐋",
    fields: [],
    defaultVolumes: ["/var/run/docker.sock:/var/run/docker.sock", "portainer_data:/data"],
  },
  {
    id: "pgadmin",
    name: "pgAdmin",
    image: "dpage/pgadmin4",
    category: "devtools",
    description: "Web-based administration tool for PostgreSQL databases.",
    defaultPort: 5050,
    icon: "🐘",
    fields: [
      { key: "PGADMIN_DEFAULT_EMAIL",    label: "Admin email",    type: "string", default: "admin@admin.com", isEnvVar: true },
      { key: "PGADMIN_DEFAULT_PASSWORD", label: "Admin password", type: "string", default: "password",        isEnvVar: true },
    ],
    defaultVolumes: ["pgadmin_data:/var/lib/pgadmin"],
  },
  {
    id: "mongo-express",
    name: "Mongo Express",
    image: "mongo-express",
    category: "devtools",
    description: "Web-based MongoDB admin interface.",
    defaultPort: 8081,
    icon: "🍃",
    fields: [
      { key: "ME_CONFIG_MONGODB_ADMINUSERNAME", label: "MongoDB username", type: "string", default: "admin",    isEnvVar: true },
      { key: "ME_CONFIG_MONGODB_ADMINPASSWORD", label: "MongoDB password", type: "string", default: "password", isEnvVar: true },
      { key: "ME_CONFIG_MONGODB_URL",           label: "MongoDB URL",      type: "string", default: "mongodb://admin:password@mongodb:27017/", isEnvVar: true },
    ],
  },
  {
    id: "redisinsight",
    name: "RedisInsight",
    image: "redis/redisinsight",
    category: "devtools",
    description: "GUI for Redis — visualize, optimize, and debug your data.",
    defaultPort: 5540,
    icon: "⚡",
    fields: [],
    defaultVolumes: ["redisinsight_data:/data"],
  },
  {
    id: "swagger-ui",
    name: "Swagger UI",
    image: "swaggerapi/swagger-ui",
    category: "devtools",
    description: "Visualize and interact with your REST API documentation.",
    defaultPort: 8080,
    icon: "📄",
    fields: [
      { key: "SWAGGER_JSON_URL", label: "OpenAPI spec URL", type: "string", default: "https://petstore.swagger.io/v2/swagger.json", isEnvVar: true },
    ],
  },
  {
    id: "sonarqube",
    name: "SonarQube",
    image: "sonarqube",
    category: "devtools",
    description: "Code quality and security analysis platform.",
    defaultPort: 9000,
    icon: "🔬",
    fields: [],
    defaultVolumes: ["sonarqube_data:/opt/sonarqube/data", "sonarqube_logs:/opt/sonarqube/logs"],
  },
  {
    id: "gitea",
    name: "Gitea",
    image: "gitea/gitea",
    category: "devtools",
    description: "Self-hosted Git service — lightweight GitHub alternative.",
    defaultPort: 3000,
    icon: "🫖",
    fields: [
      { key: "GITEA__database__DB_TYPE", label: "DB type", type: "string", default: "sqlite3", isEnvVar: true },
    ],
    defaultVolumes: ["gitea_data:/data"],
  },
  {
    id: "n8n",
    name: "n8n",
    image: "n8nio/n8n",
    category: "devtools",
    description: "Workflow automation tool — self-hosted Zapier alternative.",
    defaultPort: 5678,
    icon: "🔗",
    fields: [],
    defaultVolumes: ["n8n_data:/home/node/.n8n"],
  },

  // ── Python / Data Science ─────────────────────────────────────────────
  {
    id: "jupyterlab",
    name: "JupyterLab",
    image: "jupyter/scipy-notebook",
    category: "python",
    description: "Interactive development environment for notebooks, code, and data.",
    defaultPort: 8888,
    icon: "🪐",
    fields: [
      { key: "JUPYTER_ENABLE_LAB", label: "Enable Lab UI", type: "string", default: "yes", isEnvVar: true },
    ],
    defaultVolumes: ["jupyter_data:/home/jovyan/work"],
  },
  {
    id: "flower",
    name: "Flower (Celery)",
    image: "mher/flower",
    category: "python",
    description: "Real-time monitoring tool for Celery distributed task queues.",
    defaultPort: 5555,
    icon: "🌸",
    fields: [
      { key: "CELERY_BROKER_URL", label: "Broker URL", type: "string", default: "redis://redis:6379/0", isEnvVar: true },
    ],
  },
];

export const CATEGORIES = [
  { id: "all",        label: "All" },
  { id: "database",  label: "Databases" },
  { id: "cache",     label: "Cache" },
  { id: "messaging", label: "Messaging" },
  { id: "webserver", label: "Web Servers" },
  { id: "monitoring",label: "Monitoring" },
  { id: "devtools",  label: "Dev Tools" },
  { id: "python",    label: "Python" },
] as const;
