import type { ServiceInstance, ComposeProject } from "./types";

function escapeYamlValue(value: string | number | boolean): string {
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  // Quote strings that need it
  if (/[:#\[\]{},&*?|<>=!%@`]/.test(value) || value.includes('"') || value === "") {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

export function generateYaml(project: ComposeProject): string {
  const lines: string[] = [];

  lines.push(`# Generated by Docker Compose Generator`);
  lines.push(`# https://johangarcia.dev/projects/docker-compose-gen`);
  lines.push(``);
  lines.push(`name: ${escapeYamlValue(project.name || "my-project")}`);
  lines.push(``);
  lines.push(`services:`);

  for (const svc of project.services) {
    lines.push(`  ${svc.serviceName}:`);
    lines.push(`    image: ${svc.image}:${svc.imageTag}`);

    if (svc.restart !== "no") {
      lines.push(`    restart: ${svc.restart}`);
    }

    if (svc.ports.length > 0) {
      lines.push(`    ports:`);
      for (const p of svc.ports) {
        lines.push(`      - "${p.host}:${p.container}"`);
      }
    }

    if (svc.environment.length > 0) {
      lines.push(`    environment:`);
      for (const e of svc.environment) {
        lines.push(`      ${e.key}: ${escapeYamlValue(e.value)}`);
      }
    }

    if (svc.volumes.length > 0) {
      lines.push(`    volumes:`);
      for (const v of svc.volumes) {
        lines.push(`      - ${v.host}:${v.container}`);
      }
    }
  }

  // Named volumes
  const namedVolumes = new Set<string>();
  for (const svc of project.services) {
    for (const v of svc.volumes) {
      // Named volume = no leading . or /
      if (!v.host.startsWith(".") && !v.host.startsWith("/")) {
        namedVolumes.add(v.host);
      }
    }
  }

  if (namedVolumes.size > 0) {
    lines.push(``);
    lines.push(`volumes:`);
    for (const vol of namedVolumes) {
      lines.push(`  ${vol}:`);
    }
  }

  return lines.join("\n");
}

export function highlightYaml(yaml: string): string {
  return yaml
    .split("\n")
    .map((line) => {
      // Comments
      if (/^\s*#/.test(line)) {
        return `<span class="yaml-comment">${escapeHtml(line)}</span>`;
      }
      // Key: value
      const kvMatch = line.match(/^(\s*)([\w.-]+)(:)(\s*)(.*)$/);
      if (kvMatch) {
        const [, indent, key, colon, space, rest] = kvMatch;
        const escapedKey = escapeHtml(key);
        const escapedRest = colorizeValue(rest);
        return `${escapeHtml(indent)}<span class="yaml-key">${escapedKey}</span><span class="yaml-indent">${colon}${space}</span>${escapedRest}`;
      }
      // List item
      const listMatch = line.match(/^(\s*- )(.*)$/);
      if (listMatch) {
        const [, bullet, rest] = listMatch;
        return `<span class="yaml-indent">${escapeHtml(bullet)}</span>${colorizeValue(rest)}`;
      }
      return escapeHtml(line);
    })
    .join("\n");
}

function colorizeValue(val: string): string {
  if (!val) return "";
  const trimmed = val.trim();
  if (trimmed === "true" || trimmed === "false") {
    return `<span class="yaml-bool">${escapeHtml(val)}</span>`;
  }
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) {
    return `<span class="yaml-number">${escapeHtml(val)}</span>`;
  }
  return `<span class="yaml-string">${escapeHtml(val)}</span>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

let _idCounter = 0;
export function newId(): string {
  return `svc_${Date.now()}_${++_idCounter}`;
}
